fos_user:
    db_driver:                  orm
    firewall_name:              main
    user_class:                 %imatic_user.entity.user.class%
    group:
        group_class:            %imatic_user.entity.group.class%
    profile:
        form:
            type:               imatic_user_profile
