imports:
    - { resource: fos_user.yml }

imatic_user:
    entities:
        user: AppUserBundle\Entity\User
        group: AppUserBundle\Entity\Group

security:
    role_hierarchy:
        ROLE_IMATIC_USER_USER_ADMIN: ~
