parameters:
    imatic_user.entity.user.class:      'App\Bundle\UserBundle\Entity\User'
    imatic_user.entity.group.class:     'App\Bundle\UserBundle\Entity\Group'

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     %imatic_user.entity.user.class%

    group:
        group_class: %imatic_user.entity.group.class%

    profile:
        form:
            type: imatic_user_profile

security:
    role_hierarchy:
        ROLE_SUPER_ADMIN:   [ROLE_ALLOWED_TO_SWITCH]
