fos_user:
    db_driver:                  orm
    firewall_name:              main
    profile:
        form:
            type:               imatic_user_profile
    change_password:
        form:
            type:               imatic_user_change_password
#
#    from_email:
#        address:                %app.mailer.from.address%
#        sender_name:            %app.mailer.from.address%