fos_user:
    db_driver:                  orm
    firewall_name:              main
    profile:
        form:
            type:               imatic_user_profile
    change_password:
        form:
            type:               imatic_user_change_password