fos_user:
    db_driver:                  orm
    firewall_name:              main
    profile:
        form:
            type:               Imatic\Bundle\UserBundle\Form\Type\User\ProfileType
    change_password:
        form:
            type:               Imatic\Bundle\UserBundle\Form\Type\User\ChangePasswordType
#
#    from_email:
#        address:                "%app.mailer.from.address%"
#        sender_name:            "%app.mailer.from.address%"