imatic_user_user:
    resource: '@ImaticUserBundle/Controller/UserController.php'
    type: annotation

imatic_user_role:
    resource: '@ImaticUserBundle/Controller/RoleController.php'
    type: annotation

imatic_user_profile:
    resource: '@ImaticUserBundle/Controller/ProfileController.php'
    type: annotation

imatic_user_change_password:
    resource: '@ImaticUserBundle/Controller/ChangePasswordController.php'
    type: annotation

imatic_user_resetting:
    resource: '@ImaticUserBundle/Controller/ResettingController.php'
    type: annotation

imatic_user_security:
    resource: '@ImaticUserBundle/Controller/SecurityController.php'
    type: annotation
