services:
    _defaults:
        autowire: true      
        autoconfigure: true 
        
    Imatic\Bundle\UserBundle\Controller\:
        resource: '../../Controller/'
        tags: [ 'controller.service_arguments' ]

    Imatic\Bundle\UserBundle\Security\Role\Provider\ChainRoleProvider:
    Imatic\Bundle\UserBundle\Security\Role\Translation\RoleTranslator:

    imatic_user.user_provider.username_email:
        class: Imatic\Bundle\UserBundle\Security\EmailUserProvider

    Imatic\Bundle\UserBundle\Manager\UserManager:
        arguments:
            $userClass: '%imatic_user.entity.user.class%'

    Imatic\Bundle\UserBundle\Manager\GroupManager:
        arguments:
            $groupClass: '%imatic_user.entity.group.class%'
