parameters:
    imatic_user.admin.user.class:       'Imatic\Bundle\UserBundle\Admin\UserAdmin'
    imatic_user.admin.group.class:      'Imatic\Bundle\UserBundle\Admin\GroupAdmin'

    imatic_user.controller.user.class:  'SonataAdminBundle:CRUD'
    imatic_user.controller.group.class: 'SonataAdminBundle:CRUD'

services:
    # Sonata admin
    imatic_user.admin.user:
        class: %imatic_user.admin.user.class%
        arguments:
            - ~
            - %imatic_user.entity.user.class%
            - %imatic_user.controller.user.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: imatic_user.group.user, label: User }
        calls:
            - [ setUserManager, [@fos_user.user_manager] ]

    imatic_user.admin.group:
        class: %imatic_user.admin.group.class%
        arguments:
            - ~
            - %imatic_user.entity.group.class%
            - %imatic_user.controller.group.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: imatic_user.group.user, label: Group }

    # Form
    imatic_user.profile.form.type:
        class: Imatic\Bundle\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: imatic_user_profile }

    sonata.user.form.type.security_roles:
        class: 'Imatic\Bundle\UserBundle\Form\Type\SecurityRolesType'
        arguments:
            - @sonata.admin.pool
        tags:
            - { name: form.type, alias: sonata_security_roles }

    # Menu
    imatic_user.menu.user_menu:
        class: Imatic\Bundle\UserBundle\Menu\UserMenuBuilder
        tags:
            - { name: imatic_view.menu, alias: imatic.user }

    # Twig
    imatic_user.twig.extension.convert_roles:
        class: Imatic\Bundle\UserBundle\Twig\Extension\RoleExtension
        arguments:
            - @imatic_user.helper.role_helper
        tags:
            - { name: twig.extension }

    # Helper
    imatic_user.helper.role_helper:
        class: Imatic\Bundle\UserBundle\Helper\RoleHelper
        arguments:
            - @translator
            - %security.role_hierarchy.roles%