parameters:
    imatic_user.controller.user.class: ImaticUserBundle:Crud
    imatic_user.controller.group.class: ImaticUserBundle:Crud

services:
    # Form
    imatic_user.profile.form.type:
        class: Imatic\Bundle\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - {name: form.type, alias: imatic_user_profile}

    # Menu
    imatic_user.menu.user_menu:
        class: Imatic\Bundle\UserBundle\Menu\UserMenuBuilder
        tags:
            - {name: imatic_view.menu, alias: imatic.user}
            - {name: imatic_view.menu, alias: imatic.user_anon, method: getMenuAnon}

    imatic_user.twig.extension.security:
        class: Imatic\Bundle\UserBundle\Twig\Extension\SecurityExtension
        arguments:
            - @imatic_user.security.role.provider.model_role_provider
            - @imatic_user.security.role.translation.role_translator
        tags:
            - {name: twig.extension}

    # Security
    imatic_user.security.role.metadata_factory:
        class: Doctrine\Common\Persistence\Mapping\ClassMetadataFactory
        factory_service: doctrine.orm.entity_manager
        factory_method: getMetadataFactory

    imatic_user.security.role.provider.model_role_provider:
        class: Imatic\Bundle\UserBundle\Security\Role\Provider\ModelRoleProvider
        arguments: [@imatic_user.security.role.metadata_factory]
        public: false
        tags:
            - {name: imatic_user.role_provider}

    imatic_user.security.role.provider.hierarchy_role_provider:
        class: Imatic\Bundle\UserBundle\Security\Role\Provider\HierarchyRoleProvider
        arguments: [%security.role_hierarchy.roles%]
        tags:
            - {name: imatic_user.role_provider}

    imatic_user.security.role.provider.sonata_role_provider:
        class: Imatic\Bundle\UserBundle\Security\Role\Provider\SonataRoleProvider
        arguments: [@sonata.admin.pool]
        tags:
            - {name: imatic_user.role_provider}

    imatic_user.security.role.provider.chain_role_provider:
        class: Imatic\Bundle\UserBundle\Security\Role\Provider\ChainRoleProvider

    imatic_user.security.role.translation.role_translator:
        class: Imatic\Bundle\UserBundle\Security\Role\Translation\RoleTranslator
        arguments: [@translator]

    imatic_user.security.role.translation.object_strategy:
        class: Imatic\Bundle\UserBundle\Security\Role\Translation\ObjectStrategy
        arguments: [@translator, @sonata.admin.label.strategy.native]
        tags:
            - {name: imatic_user.role_translation_strategy}

    imatic_user.security.role.translation.hierarchy_strategy:
        class: Imatic\Bundle\UserBundle\Security\Role\Translation\HierarchyStrategy
        arguments: [@translator]
        tags:
            - {name: imatic_user.role_translation_strategy}

    imatic.model_role_provider:
        alias: imatic_user.security.role.provider.model_role_provider

    imatic.hierarchy_role_provider:
        alias: imatic_user.security.role.provider.hierarchy_role_provider

    imatic.sonata_role_provider:
        alias: imatic_user.security.role.provider.sonata_role_provider

    imatic.role_provider:
        alias: imatic_user.security.role.provider.chain_role_provider